[package]
name = "lyric"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-bert = "0.21.0"
clap = {version="4.3.19",features=["derive"]}
sqlite = "0.31.0"
torch-sys = "0.13.0"
